language: java
jdk: oraclejdk7

notifications:
  email: false

before_install:
 - chmod a+x ./travis/install-prerequisites.sh
install:
 - ./travis/install-prerequisites.sh

before_script:
 - chmod a+x ./travis/build.sh
script:
 - ./travis/build.sh
